[project]
name = "bert"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    torch==2.0.1+cu118
    pytorch-lightning==1.9.0
    transformers==4.30.0
    datasets==2.13.1
    scikit-learn==1.2.2
    wandb==0.15.0
]